apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsonproducer
  namespace: default
  labels:
    app: jsonproducer
spec:
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: jsonproducer
  template:
    metadata:
      labels:
        app: jsonproducer
    spec:
      containers:
      - name: jsonproducer
        image: ualmtorres/jsonproducer:v0
        ports:
        - name: http
          containerPort: 80
